/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Trackstar Game API
 * Multiplayer music guessing game API with buzz-in mechanics
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiSessionsId200,
  GetApiSessionsId404,
  GetApiSessionsIdParams,
  PostApiSessions200,
  PostApiSessions400,
  PostApiSessionsBody
} from '.././model';

import { customFetch } from '.././mutator';
import type { ErrorType } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new game session
 * @summary Create session
 */
export type postApiSessionsResponse200 = {
  data: PostApiSessions200
  status: 200
}

export type postApiSessionsResponse400 = {
  data: PostApiSessions400
  status: 400
}
    
export type postApiSessionsResponseSuccess = (postApiSessionsResponse200) & {
  headers: Headers;
};
export type postApiSessionsResponseError = (postApiSessionsResponse400) & {
  headers: Headers;
};

export type postApiSessionsResponse = (postApiSessionsResponseSuccess | postApiSessionsResponseError)

export const getPostApiSessionsUrl = () => {


  

  return `/api/sessions`
}

export const postApiSessions = async (postApiSessionsBody: PostApiSessionsBody, options?: RequestInit): Promise<postApiSessionsResponse> => {
  
  return customFetch<postApiSessionsResponse>(getPostApiSessionsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiSessionsBody,)
  }
);}




export const getPostApiSessionsMutationOptions = <TError = ErrorType<PostApiSessions400>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessions>>, TError,{data: PostApiSessionsBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSessions>>, TError,{data: PostApiSessionsBody}, TContext> => {

const mutationKey = ['postApiSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSessions>>, {data: PostApiSessionsBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiSessions(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSessions>>>
    export type PostApiSessionsMutationBody = PostApiSessionsBody
    export type PostApiSessionsMutationError = ErrorType<PostApiSessions400>

    /**
 * @summary Create session
 */
export const usePostApiSessions = <TError = ErrorType<PostApiSessions400>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessions>>, TError,{data: PostApiSessionsBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSessions>>,
        TError,
        {data: PostApiSessionsBody},
        TContext
      > => {

      const mutationOptions = getPostApiSessionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get session details with optional includes
 * @summary Get session
 */
export type getApiSessionsIdResponse200 = {
  data: GetApiSessionsId200
  status: 200
}

export type getApiSessionsIdResponse404 = {
  data: GetApiSessionsId404
  status: 404
}
    
export type getApiSessionsIdResponseSuccess = (getApiSessionsIdResponse200) & {
  headers: Headers;
};
export type getApiSessionsIdResponseError = (getApiSessionsIdResponse404) & {
  headers: Headers;
};

export type getApiSessionsIdResponse = (getApiSessionsIdResponseSuccess | getApiSessionsIdResponseError)

export const getGetApiSessionsIdUrl = (id: string,
    params?: GetApiSessionsIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sessions/${id}?${stringifiedParams}` : `/api/sessions/${id}`
}

export const getApiSessionsId = async (id: string,
    params?: GetApiSessionsIdParams, options?: RequestInit): Promise<getApiSessionsIdResponse> => {
  
  return customFetch<getApiSessionsIdResponse>(getGetApiSessionsIdUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiSessionsIdQueryKey = (id?: string,
    params?: GetApiSessionsIdParams,) => {
    return [
    `/api/sessions/${id}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiSessionsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = ErrorType<GetApiSessionsId404>>(id: string,
    params?: GetApiSessionsIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsIdQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessionsId>>> = ({ signal }) => getApiSessionsId(id,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessionsId>>>
export type GetApiSessionsIdQueryError = ErrorType<GetApiSessionsId404>


export function useGetApiSessionsId<TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = ErrorType<GetApiSessionsId404>>(
 id: string,
    params: undefined |  GetApiSessionsIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsId<TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = ErrorType<GetApiSessionsId404>>(
 id: string,
    params?: GetApiSessionsIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsId<TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = ErrorType<GetApiSessionsId404>>(
 id: string,
    params?: GetApiSessionsIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get session
 */

export function useGetApiSessionsId<TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = ErrorType<GetApiSessionsId404>>(
 id: string,
    params?: GetApiSessionsIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsIdQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




