/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Trackstar Game API
 * Multiplayer music guessing game API with buzz-in mechanics
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiSessionsIdPlayers200Item,
  GetApiSessionsIdPlayersParams,
  PostApiSessionsIdPlayers200,
  PostApiSessionsIdPlayersBody
} from '.././model';

import { customFetch } from '.././mutator';
import type { ErrorType } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Join a game session as a player
 * @summary Join session
 */
export type postApiSessionsIdPlayersResponse200 = {
  data: PostApiSessionsIdPlayers200
  status: 200
}

export type postApiSessionsIdPlayersResponse400 = {
  data: void
  status: 400
}

export type postApiSessionsIdPlayersResponse404 = {
  data: void
  status: 404
}
    
export type postApiSessionsIdPlayersResponseSuccess = (postApiSessionsIdPlayersResponse200) & {
  headers: Headers;
};
export type postApiSessionsIdPlayersResponseError = (postApiSessionsIdPlayersResponse400 | postApiSessionsIdPlayersResponse404) & {
  headers: Headers;
};

export type postApiSessionsIdPlayersResponse = (postApiSessionsIdPlayersResponseSuccess | postApiSessionsIdPlayersResponseError)

export const getPostApiSessionsIdPlayersUrl = (id: string,) => {


  

  return `/api/sessions/${id}/players`
}

export const postApiSessionsIdPlayers = async (id: string,
    postApiSessionsIdPlayersBody: PostApiSessionsIdPlayersBody, options?: RequestInit): Promise<postApiSessionsIdPlayersResponse> => {
  
  return customFetch<postApiSessionsIdPlayersResponse>(getPostApiSessionsIdPlayersUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiSessionsIdPlayersBody,)
  }
);}




export const getPostApiSessionsIdPlayersMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessionsIdPlayers>>, TError,{id: string;data: PostApiSessionsIdPlayersBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSessionsIdPlayers>>, TError,{id: string;data: PostApiSessionsIdPlayersBody}, TContext> => {

const mutationKey = ['postApiSessionsIdPlayers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSessionsIdPlayers>>, {id: string;data: PostApiSessionsIdPlayersBody}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiSessionsIdPlayers(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiSessionsIdPlayersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSessionsIdPlayers>>>
    export type PostApiSessionsIdPlayersMutationBody = PostApiSessionsIdPlayersBody
    export type PostApiSessionsIdPlayersMutationError = ErrorType<void>

    /**
 * @summary Join session
 */
export const usePostApiSessionsIdPlayers = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessionsIdPlayers>>, TError,{id: string;data: PostApiSessionsIdPlayersBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSessionsIdPlayers>>,
        TError,
        {id: string;data: PostApiSessionsIdPlayersBody},
        TContext
      > => {

      const mutationOptions = getPostApiSessionsIdPlayersMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List all players in a session
 * @summary List players
 */
export type getApiSessionsIdPlayersResponse200 = {
  data: GetApiSessionsIdPlayers200Item[]
  status: 200
}
    
export type getApiSessionsIdPlayersResponseSuccess = (getApiSessionsIdPlayersResponse200) & {
  headers: Headers;
};
;

export type getApiSessionsIdPlayersResponse = (getApiSessionsIdPlayersResponseSuccess)

export const getGetApiSessionsIdPlayersUrl = (id: string,
    params?: GetApiSessionsIdPlayersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sessions/${id}/players?${stringifiedParams}` : `/api/sessions/${id}/players`
}

export const getApiSessionsIdPlayers = async (id: string,
    params?: GetApiSessionsIdPlayersParams, options?: RequestInit): Promise<getApiSessionsIdPlayersResponse> => {
  
  return customFetch<getApiSessionsIdPlayersResponse>(getGetApiSessionsIdPlayersUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiSessionsIdPlayersQueryKey = (id?: string,
    params?: GetApiSessionsIdPlayersParams,) => {
    return [
    `/api/sessions/${id}/players`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiSessionsIdPlayersQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessionsIdPlayers>>, TError = ErrorType<unknown>>(id: string,
    params?: GetApiSessionsIdPlayersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdPlayers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsIdPlayersQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessionsIdPlayers>>> = ({ signal }) => getApiSessionsIdPlayers(id,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdPlayers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsIdPlayersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessionsIdPlayers>>>
export type GetApiSessionsIdPlayersQueryError = ErrorType<unknown>


export function useGetApiSessionsIdPlayers<TData = Awaited<ReturnType<typeof getApiSessionsIdPlayers>>, TError = ErrorType<unknown>>(
 id: string,
    params: undefined |  GetApiSessionsIdPlayersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdPlayers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsIdPlayers>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsIdPlayers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsIdPlayers<TData = Awaited<ReturnType<typeof getApiSessionsIdPlayers>>, TError = ErrorType<unknown>>(
 id: string,
    params?: GetApiSessionsIdPlayersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdPlayers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsIdPlayers>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsIdPlayers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsIdPlayers<TData = Awaited<ReturnType<typeof getApiSessionsIdPlayers>>, TError = ErrorType<unknown>>(
 id: string,
    params?: GetApiSessionsIdPlayersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdPlayers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List players
 */

export function useGetApiSessionsIdPlayers<TData = Awaited<ReturnType<typeof getApiSessionsIdPlayers>>, TError = ErrorType<unknown>>(
 id: string,
    params?: GetApiSessionsIdPlayersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdPlayers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsIdPlayersQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




