/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Trackstar Game API
 * Multiplayer music guessing game API with buzz-in mechanics
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSessionsId200PlayersItem } from './getApiSessionsId200PlayersItem';
import type { GetApiSessionsId200RoundsItem } from './getApiSessionsId200RoundsItem';
import type { GetApiSessionsId200Pack } from './getApiSessionsId200Pack';

export type GetApiSessionsId200 = {
  id: string;
  code: string;
  state: string;
  current_round: number;
  players?: GetApiSessionsId200PlayersItem[];
  rounds?: GetApiSessionsId200RoundsItem[];
  /** @nullable */
  pack?: GetApiSessionsId200Pack;
};
