/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Trackstar Game API
 * Multiplayer music guessing game API with buzz-in mechanics
 * OpenAPI spec version: 1.0.0
 */

export type GetApiSessionsIdPlayers200Item = {
  id: string;
  session_id: string;
  name: string;
  score: number;
  joined_at: string;
};
