/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Trackstar Game API
 * Multiplayer music guessing game API with buzz-in mechanics
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSessionsIdPlayersSort } from './getApiSessionsIdPlayersSort';
import type { GetApiSessionsIdPlayersOrder } from './getApiSessionsIdPlayersOrder';

export type GetApiSessionsIdPlayersParams = {
sort?: GetApiSessionsIdPlayersSort;
order?: GetApiSessionsIdPlayersOrder;
};
