/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Trackstar Game API
 * Multiplayer music guessing game API with buzz-in mechanics
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPacks200ItemTracksItem } from './getApiPacks200ItemTracksItem';

export type GetApiPacks200Item = {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  is_active: boolean;
  created_at: string;
  track_count?: number;
  tracks?: GetApiPacks200ItemTracksItem[];
};
