/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Trackstar Game API
 * Multiplayer music guessing game API with buzz-in mechanics
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetApiSessionsId200Pack = unknown | null;
