/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Trackstar Game API
 * Multiplayer music guessing game API with buzz-in mechanics
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiSessionsIdRoundsCurrentBodyOneOfAction = typeof PatchApiSessionsIdRoundsCurrentBodyOneOfAction[keyof typeof PatchApiSessionsIdRoundsCurrentBodyOneOfAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiSessionsIdRoundsCurrentBodyOneOfAction = {
  start: 'start',
} as const;
