/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Trackstar Game API
 * Multiplayer music guessing game API with buzz-in mechanics
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiSessions200State } from './postApiSessions200State';

export type PostApiSessions200 = {
  id: string;
  code: string;
  host_name: string;
  pack_id: string;
  state: PostApiSessions200State;
  current_round: number;
  /** @nullable */
  round_start_time: string | null;
  created_at: string;
};
