/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Trackstar Game API
 * Multiplayer music guessing game API with buzz-in mechanics
 * OpenAPI spec version: 1.0.0
 */

export type PostApiSessions200State = typeof PostApiSessions200State[keyof typeof PostApiSessions200State];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiSessions200State = {
  lobby: 'lobby',
  ready: 'ready',
  playing: 'playing',
  buzzed: 'buzzed',
  reveal: 'reveal',
  finished: 'finished',
} as const;
