/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Trackstar Game API
 * Multiplayer music guessing game API with buzz-in mechanics
 * OpenAPI spec version: 1.0.0
 */

export type PostApiSessionsIdRoundsCurrentBuzz200 = {
  id: string;
  session_id: string;
  round_number: number;
  track_id: string;
  /** @nullable */
  buzzer_player_id: string | null;
  /** @nullable */
  elapsed_seconds: number | null;
  /** @nullable */
  was_correct: boolean | null;
  /** @nullable */
  points_awarded: number | null;
};
