/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Trackstar Game API
 * Multiplayer music guessing game API with buzz-in mechanics
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiPacks200Item,
  GetApiPacksParams
} from '.././model';

import { customFetch } from '.././mutator';
import type { ErrorType } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List all music packs with optional includes
 * @summary List packs
 */
export type getApiPacksResponse200 = {
  data: GetApiPacks200Item[]
  status: 200
}
    
export type getApiPacksResponseSuccess = (getApiPacksResponse200) & {
  headers: Headers;
};
;

export type getApiPacksResponse = (getApiPacksResponseSuccess)

export const getGetApiPacksUrl = (params?: GetApiPacksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/packs?${stringifiedParams}` : `/api/packs`
}

export const getApiPacks = async (params?: GetApiPacksParams, options?: RequestInit): Promise<getApiPacksResponse> => {
  
  return customFetch<getApiPacksResponse>(getGetApiPacksUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiPacksQueryKey = (params?: GetApiPacksParams,) => {
    return [
    `/api/packs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiPacksQueryOptions = <TData = Awaited<ReturnType<typeof getApiPacks>>, TError = ErrorType<unknown>>(params?: GetApiPacksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPacks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPacksQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPacks>>> = ({ signal }) => getApiPacks(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPacks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPacksQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPacks>>>
export type GetApiPacksQueryError = ErrorType<unknown>


export function useGetApiPacks<TData = Awaited<ReturnType<typeof getApiPacks>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiPacksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPacks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPacks>>,
          TError,
          Awaited<ReturnType<typeof getApiPacks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPacks<TData = Awaited<ReturnType<typeof getApiPacks>>, TError = ErrorType<unknown>>(
 params?: GetApiPacksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPacks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPacks>>,
          TError,
          Awaited<ReturnType<typeof getApiPacks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPacks<TData = Awaited<ReturnType<typeof getApiPacks>>, TError = ErrorType<unknown>>(
 params?: GetApiPacksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPacks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List packs
 */

export function useGetApiPacks<TData = Awaited<ReturnType<typeof getApiPacks>>, TError = ErrorType<unknown>>(
 params?: GetApiPacksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPacks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPacksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




