/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Trackstar Game API
 * Multiplayer music guessing game API with buzz-in mechanics
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PatchApiSessionsIdRoundsCurrentBody,
  PostApiSessionsIdRoundsCurrentBuzz200,
  PostApiSessionsIdRoundsCurrentBuzzBody
} from '.././model';

import { customFetch } from '.././mutator';
import type { ErrorType } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Player buzzes in during current round
 * @summary Buzz in
 */
export type postApiSessionsIdRoundsCurrentBuzzResponse200 = {
  data: PostApiSessionsIdRoundsCurrentBuzz200
  status: 200
}

export type postApiSessionsIdRoundsCurrentBuzzResponse400 = {
  data: void
  status: 400
}

export type postApiSessionsIdRoundsCurrentBuzzResponse404 = {
  data: void
  status: 404
}
    
export type postApiSessionsIdRoundsCurrentBuzzResponseSuccess = (postApiSessionsIdRoundsCurrentBuzzResponse200) & {
  headers: Headers;
};
export type postApiSessionsIdRoundsCurrentBuzzResponseError = (postApiSessionsIdRoundsCurrentBuzzResponse400 | postApiSessionsIdRoundsCurrentBuzzResponse404) & {
  headers: Headers;
};

export type postApiSessionsIdRoundsCurrentBuzzResponse = (postApiSessionsIdRoundsCurrentBuzzResponseSuccess | postApiSessionsIdRoundsCurrentBuzzResponseError)

export const getPostApiSessionsIdRoundsCurrentBuzzUrl = (id: string,) => {


  

  return `/api/sessions/${id}/rounds/current/buzz`
}

export const postApiSessionsIdRoundsCurrentBuzz = async (id: string,
    postApiSessionsIdRoundsCurrentBuzzBody: PostApiSessionsIdRoundsCurrentBuzzBody, options?: RequestInit): Promise<postApiSessionsIdRoundsCurrentBuzzResponse> => {
  
  return customFetch<postApiSessionsIdRoundsCurrentBuzzResponse>(getPostApiSessionsIdRoundsCurrentBuzzUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiSessionsIdRoundsCurrentBuzzBody,)
  }
);}




export const getPostApiSessionsIdRoundsCurrentBuzzMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessionsIdRoundsCurrentBuzz>>, TError,{id: string;data: PostApiSessionsIdRoundsCurrentBuzzBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSessionsIdRoundsCurrentBuzz>>, TError,{id: string;data: PostApiSessionsIdRoundsCurrentBuzzBody}, TContext> => {

const mutationKey = ['postApiSessionsIdRoundsCurrentBuzz'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSessionsIdRoundsCurrentBuzz>>, {id: string;data: PostApiSessionsIdRoundsCurrentBuzzBody}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiSessionsIdRoundsCurrentBuzz(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiSessionsIdRoundsCurrentBuzzMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSessionsIdRoundsCurrentBuzz>>>
    export type PostApiSessionsIdRoundsCurrentBuzzMutationBody = PostApiSessionsIdRoundsCurrentBuzzBody
    export type PostApiSessionsIdRoundsCurrentBuzzMutationError = ErrorType<void>

    /**
 * @summary Buzz in
 */
export const usePostApiSessionsIdRoundsCurrentBuzz = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessionsIdRoundsCurrentBuzz>>, TError,{id: string;data: PostApiSessionsIdRoundsCurrentBuzzBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSessionsIdRoundsCurrentBuzz>>,
        TError,
        {id: string;data: PostApiSessionsIdRoundsCurrentBuzzBody},
        TContext
      > => {

      const mutationOptions = getPostApiSessionsIdRoundsCurrentBuzzMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Update current round state (start, judge, reveal)
 * @summary Update current round
 */
export type patchApiSessionsIdRoundsCurrentResponse200 = {
  data: void
  status: 200
}

export type patchApiSessionsIdRoundsCurrentResponse400 = {
  data: void
  status: 400
}
    
export type patchApiSessionsIdRoundsCurrentResponseSuccess = (patchApiSessionsIdRoundsCurrentResponse200) & {
  headers: Headers;
};
export type patchApiSessionsIdRoundsCurrentResponseError = (patchApiSessionsIdRoundsCurrentResponse400) & {
  headers: Headers;
};

export type patchApiSessionsIdRoundsCurrentResponse = (patchApiSessionsIdRoundsCurrentResponseSuccess | patchApiSessionsIdRoundsCurrentResponseError)

export const getPatchApiSessionsIdRoundsCurrentUrl = (id: string,) => {


  

  return `/api/sessions/${id}/rounds/current`
}

export const patchApiSessionsIdRoundsCurrent = async (id: string,
    patchApiSessionsIdRoundsCurrentBody: PatchApiSessionsIdRoundsCurrentBody, options?: RequestInit): Promise<patchApiSessionsIdRoundsCurrentResponse> => {
  
  return customFetch<patchApiSessionsIdRoundsCurrentResponse>(getPatchApiSessionsIdRoundsCurrentUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchApiSessionsIdRoundsCurrentBody,)
  }
);}




export const getPatchApiSessionsIdRoundsCurrentMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiSessionsIdRoundsCurrent>>, TError,{id: string;data: PatchApiSessionsIdRoundsCurrentBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiSessionsIdRoundsCurrent>>, TError,{id: string;data: PatchApiSessionsIdRoundsCurrentBody}, TContext> => {

const mutationKey = ['patchApiSessionsIdRoundsCurrent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiSessionsIdRoundsCurrent>>, {id: string;data: PatchApiSessionsIdRoundsCurrentBody}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiSessionsIdRoundsCurrent(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiSessionsIdRoundsCurrentMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiSessionsIdRoundsCurrent>>>
    export type PatchApiSessionsIdRoundsCurrentMutationBody = PatchApiSessionsIdRoundsCurrentBody
    export type PatchApiSessionsIdRoundsCurrentMutationError = ErrorType<void>

    /**
 * @summary Update current round
 */
export const usePatchApiSessionsIdRoundsCurrent = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiSessionsIdRoundsCurrent>>, TError,{id: string;data: PatchApiSessionsIdRoundsCurrentBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiSessionsIdRoundsCurrent>>,
        TError,
        {id: string;data: PatchApiSessionsIdRoundsCurrentBody},
        TContext
      > => {

      const mutationOptions = getPatchApiSessionsIdRoundsCurrentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    